---

- name: Get a MySQL repo
  command: wget http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
  args:
    chdir: /opt/
 
- name: Install MySQL repo package.
  command: rpm -ivh /opt/mysql-community-release-el7-5.noarch.rpm  
  ignore_errors: yes
 
- name: Install EPEL
  yum:
    name: "{{item}}"
    state: latest
  with_items:
   - epel-release
 
- name: Install the latest version of packages
  yum:
    name: "{{item}}"
    state: latest
  with_items:
   - mysql-server
   - mysql-devel
   - python-devel
   - python-pip
 
- name: Install Python MySQL module
  pip: name=MySQL-python
 
- name: Start MySQL
  service: name=mysqld state=started enabled=yes
 
- name: Get list of hosts for the root user.
  command: mysql -NBe 'SELECT Host FROM mysql.user WHERE User = "root" ORDER BY (Host="localhost") ASC'
  register: mysql_root_hosts
  changed_when: false

- name: Update MySQL root password for localhost root account.
  mysql_user:
    name: "root"
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
  with_items: "{{ mysql_root_hosts.stdout_lines }}"

- name: Copy .my.cnf file with root password credentials.
  template:
    src: "user-my.cnf"
    dest: "~/.my.cnf"
    owner: root
    group: root
    mode: 0600

- name: Get list of hosts for the anonymous user.
  command: mysql -NBe 'SELECT Host FROM mysql.user WHERE User = ""'
  register: mysql_anonymous_hosts
  changed_when: false

- name: Remove anonymous MySQL users.
  mysql_user:
     name: ""
     host: "{{ item }}"
     state: absent
  with_items: "{{ mysql_anonymous_hosts.stdout_lines }}"

- name: Remove MySQL test database.
  mysql_db: "name='test' state=absent"
  
- name: Restart MySQL
  service: name=mysqld state=restarted
 